### ISSUE TITLE
Error causing server to crash.

### ISSUE THREAD

**Issue by SugarRealms** [iSach/UltraCosmetics#17] opened 2015-12-28 17:47 UTC
Here is the error: http://pastebin.com/cqPu8hMU

**Comment by iSach** [comment] 2016-01-01 16:32
Is this fixed in 2.0.3?

**Comment by xion87** [comment] 2016-01-07 18:55
not fixed got the same error spam:
http://hastebin.com/qatopamowi.avrasm
plus the followings errors (i am at offline mode)
- http://hastebin.com/ogececumaj.vbs

**Comment by Someone-NEW** [comment] 2016-01-16 23:15
Not fixed used latest version. And Hastebin cleared every 5 hours so than is not possible see what you paste here
Use pastebin or justpasteit

**Comment by iSach** [comment] 2016-01-24 11:33
Caused by Minecraft pathfinders.

**Closed by iSach** 2016-01-24 11:33 UTC
