### ISSUE TITLE
[Rocket Problem]

### ISSUE THREAD

**Issue by JamiePlayzMC** [iSach/UltraCosmetics#170] opened 2016-07-21 17:21 UTC
Hi I recently updated to the latest version and every time the rocket blows up the console spits out this

21.07 17:19:56 [Server] WARN Exception in thread "Craft Scheduler Thread - 13" 
21.07 17:19:56 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin UltraCosmetics v2.3.9 generated an exception while executing task 101
21.07 17:19:56 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
21.07 17:19:56 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
21.07 17:19:56 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
21.07 17:19:56 [Server] INFO at java.lang.Thread.run(Thread.java:745)
21.07 17:19:56 [Server] INFO Caused by: java.lang.IndexOutOfBoundsException: Index: 8, Size: 0
21.07 17:19:56 [Server] INFO at java.util.ArrayList.rangeCheck(ArrayList.java:653)
21.07 17:19:56 [Server] INFO at java.util.ArrayList.get(ArrayList.java:429)
21.07 17:19:56 [Server] INFO at be.isach.ultracosmetics.cosmetics.gadgets.GadgetRocket.onUpdate(GadgetRocket.java:171)
21.07 17:19:56 [Server] INFO at be.isach.ultracosmetics.cosmetics.gadgets.Gadget$1.run(Gadget.java:118)
21.07 17:19:56 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
21.07 17:19:56 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
21.07 17:19:56 [Server] INFO ... 3 more

**Comment by aycgit** [comment] 2016-07-22 07:53
Which spigot version are u on and can we get a full error log?

**Comment by GyllieGyllie** [comment] 2016-07-24 21:01
spigot version: 1.8.8
this is the full log, nothing more is shown in console/logs:

`[21:00:16] [Craft Scheduler Thread - 27/WARN]: Exception in thread "Craft Scheduler Thread - 27" 
[21:00:16] [Craft Scheduler Thread - 27/WARN]: org.apache.commons.lang.UnhandledException: Plugin UltraCosmetics v2.3.9 generated an exception while executing task 157
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 9, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at be.isach.ultracosmetics.cosmetics.gadgets.GadgetRocket.onUpdate(GadgetRocket.java:176)
	at be.isach.ultracosmetics.cosmetics.gadgets.Gadget$1.run(Gadget.java:118)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more
`

**Comment by aycgit** [comment] 2016-08-13 08:28
sorry for the late reply, i think the issue is fixed with the newest update, on  my server, i just took the permssion for the rocket away when it happened to me

**Comment by iSach** [comment] 2017-03-12 10:26
Are you still getting this error in last beta builds? Please reopen if yes.

ci.isach.be

**Closed by iSach** 2017-03-12 10:26 UTC
Labels: bug
