### ISSUE TITLE
Animals & mobs stuck in flat land

### ISSUE THREAD

**Issue by TeamUXRO** [iSach/UltraCosmetics#163] opened 2016-07-17 09:02 UTC
Hello.
First of all everything else works fine but this is one problem that i notice with latest build. In flat land which i created using Multiverse-Core all animals & mobs are stuck. Some slimes are stuck in air others are just standing there, even if you punch it, it won't move, it will only display damage. And other animals won't move around as they should. (sheep, cow,..)

This is related to plugin because when i remove it from plugins folder all animals & mobs start to move again. But yeah in other worlds that are not flat they work fine.

(Thanks for developing this amazing plugin, love it! Keep up the good work :D)

**Comment by iSach** [comment] 2016-07-17 11:53
Duplicate of:
https://github.com/iSach/UltraCosmetics/issues/160

**Closed by iSach** 2016-07-17 11:53 UTC
Labels: duplicate
