### ISSUE TITLE
Infinite duplication of items.

### ISSUE THREAD

**Issue by alekso56** [iSach/UltraCosmetics#95] opened 2016-05-12 22:58 UTC
Kinda urgent bug here, present on all versions. (as of 2.1.2)

To recreate the bug:
- enable ammo
- go to a world that does not have uc enabled
- open the uc menu with /uc menu gadgets
- click a gadget that does not have ammo
- drag all the free stuff to your inv, repeat as many times as you'd like.

tested on mc 1.8.8 and mc 1.9.2

**Comment by philip-ulrich** [comment] 2016-05-14 20:57
Essentially a duplicate of #77. Same offhand issues as other un-updated plugins. Not sure if he reads these because that has been stagnant for a month. Hope he fixes this with 1.9.4 because otherwise I can't use this.

**Comment by iSach** [comment] 2016-05-15 01:10
Fixed on 2.1.3

**Closed by iSach** 2016-05-15 01:10 UTC
