### ISSUE TITLE
Nyan Sheep kill the server.

### ISSUE THREAD

**Issue by SilverCory** [iSach/UltraCosmetics#29] opened 2016-01-09 16:52 UTC
Not sure why..

Here's the stack-trace. Only happens when the plugin is loaded and we're on the sheep..

http://paste.fedoraproject.org/308997/58080145/

**Comment by xion87** [comment] 2016-01-11 14:50
nyan cat still not fixed in 3.0.4, it causing crash
http://hastebin.com/asajogatim.md

**Comment by iSach** [comment] 2016-01-11 14:52
At least now its another error. Gonna try to fix this now, Mojang and their great server that crashes with a little error

**Comment by SilverCory** [comment] 2016-01-11 15:26
#BlameTicking xD
You would think they just ignore the error.

**Comment by Someone-NEW** [comment] 2016-01-16 23:11
I can Confirm Nyan Sheep chrash server i test and do that automatic walk and go to wall sheep cant go crose wall stuck and crash server i think you muss fix this. And another big problem is with Pets Names still persist problems you realy need change system for using that names while stuck and cand removed it. Here are 2 very big bugs needed to be fixed. I use latest version
Bad english sorry but i hope you can understand what is the problem ;)

**Comment by iSach** [comment] 2016-01-24 11:32
Nyan Sheep navigation is caused by Minecraft bad Pathfinding. I don't know yet how to fix it except making my own pathfinder, which I don't have time for.

**Closed by iSach** 2016-01-24 11:32 UTC

**Comment by Someone-NEW** [comment] 2016-01-24 13:59
I remove all permissions for that NyanSheep but this is not a right solution. And with names problem still the same maybe look in code from EchoPet only for ideas how to solve something i dont mean copy but only for help maybe you give some solution. this is only my suggestion

**Comment by xion87** [comment] 2016-01-25 16:04
i suggest to remove nyan sheep from the plugin, but time ago i got the same issue with echopet with 1.7-->1.8 upgrade and was fixed
