### ISSUE TITLE
Molten Snake Exception

### ISSUE THREAD

**Issue by iBuseWinner** [iSach/UltraCosmetics#474] opened 2020-03-08 20:00 UTC
### What steps will reproduce the issue?  
1. Activate Molten Snake
2. Use it
3. Deactivate

### What was supposed to happen?

No exceptions in console

### What happened? 

Exceptions in console

### What version of UltraCosmetics are you using?  
2.5.7

### What Spigot version are you using? Paste the output of /version below.  
[21:54:38 INFO]: This server is running Paper version git-Paper-121 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[21:54:38 INFO]: Checking version, please wait...
[21:54:38 INFO]: You are 8 version(s) behind

### What plugins do you have installed? Paste the output of /plugins below.  
[21:54:51 INFO]: Plugins (20): Chatty*, Citizens, CrazyCrates, DeluxeMenus, DeluxeTags*, DTCoins, DTScoreboard*, Holograms, HologramsPlaceholders*, Joiner, LibsDisguis
 PlugMan, ProtocolLib, TAB, UltraCosmetics, Vault, WorldEdit, WorldGuard

### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
```
[17:16:24 WARN]: 0cf7fbe2-b51c-4835-9d1f-fb3aae250199 (vehicle of BuseSo) moved wrongly!                                                                                
[17:17:11 WARN]: java.lang.NullPointerException
[17:17:11 WARN]:        at be.isach.ultracosmetics.cosmetics.mounts.MountMoltenSnake.onUpdate(MountMoltenSnake.java:67)
[17:17:11 WARN]:        at be.isach.ultracosmetics.cosmetics.mounts.Mount.run(Mount.java:108)
[17:17:11 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[17:17:11 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[17:17:11 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[17:17:11 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[17:17:11 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[17:17:11 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by datatags** [comment] 2021-12-31 02:54
Looks like a duplicate of #470 (though this one is more clear with the error) but it's probably fixed.

**Closed by datatags** 2021-12-31 02:54 UTC
