### ISSUE TITLE
Some newer Blocks (1.13+) disappear after Color Effect from Paintball Gun, Mount of Water etc...

### ISSUE THREAD

**Issue by Chris6ix** [iSach/UltraCosmetics#561] opened 2022-01-02 15:42 UTC
### What steps will reproduce the issue?  
1. Shoot some newer Minecraft Blocks (1.13+) like Gilded Blackstone, Moss Block, Ancient Debris, Copper Block, Bee Nest, Prismarine Stairs, Barrels etc... with the Paintball Gun or walk over them with a Mount that has some "Color Effect" like the "Mount of Water"
2. Wait a bit for the Stained Clay to disappear and see that the original block vanished...
3.Leave the Server and rejoin, now the Blocks are there again...

### What was supposed to happen?
The Blocks should stay there, just like other Block (Stone, Diamond Block, Oak Log etc...)
### What happened? 
Newer (1.13+) Blocks vanish after the color Effect and only reappear after leaving and rejoining the Server
### What version of UltraCosmetics are you using?  
2.5.11
### What Spigot version are you using? Paste the output of /version below.  
This server is running Paper version git-Paper-406 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: b1af5ea on ver/1.17.1)
### What plugins do you have installed? Paste the output of /plugins below.  
Plugins (41): BetterConcrete, Bookshelf, CommandCooldown, CustomEnderChest, DeluxeMenus, Duels, dynmap, Essentials, EssentialsChat, FlyPerms, GSit, Hat, HolographicDisplays, HoloMobHealth, HomeGUI, InteractionVisualizer, JoinRules, LightAPI, LinksPlus, LuckPerms, Multiverse-Core, Multiverse-Inventories, NexEngine, PL-Hide, PlaceholderAPI, PlayerPortal, PlayerWarps, Playtimes*, PlugMan, ProtocolLib, QuickShop, RealScoreboard, SilkSpawners, TAB, UltimateCatcher, UltimateTimber, UltraCosmetics, Vault, WorldEdit, WorldGuard, XpBottles
### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
No Errors
### Any additional information that you would like to provide that may be relevant to the issue?
No

**Comment by datatags** [comment] 2022-01-02 16:06
Duplicate of #501, which is fixed in dev builds.

**Closed by datatags** 2022-01-02 16:06 UTC
