### ISSUE TITLE
Emotes can be duped and dropped

### ISSUE THREAD

**Issue by EefCantDrown** [iSach/UltraCosmetics#562] opened 2022-01-09 09:11 UTC
### What steps will reproduce the issue?  
1. Equip any emote
2. Open inventory 
3. Spam q while hovering mouse over emote in inventory 

### What was supposed to happen?
Shouldn't even drop the head
### What happened? 
Duped and dropped emote heads on ground
### What version of UltraCosmetics are you using?  
2.5.11
### What Spigot version are you using? Paste the output of /version below.  
Paper 1.17.1  (locked to 1.17) Build 399
### What plugins do you have installed? Paste the output of /plugins below.  
BanManagerBukkit.jar 
BossTweaks-v1.1.1.jar 
BroadcastPlus-2.7.0.jar
BusinessTools-1.17.jar 
ChatChannels.jar
GMute.jar 
GPAccruals-1.1.jar 
GriefPrevention.jar 
HolographicDisplays.jar 
HubThat-10.1.184.jar
JoinMessage-1.2.jar 
Multiverse-Core-4.3.1.jar 
Multiverse-Inventories-4.2.2.jar 
OpenInv.jar 
oplogger-1.2.0.jar
oreAlert.jar
OreAnnouncer-2.8.2.jar 
PerRegionChat-1.3.jar 
PerWorldTablist.jar 
PlaceholderAPI-2.10.10.jar
Playtime-1.10.0.jar 
PluginConstructorAPI.jar 
PowerRanks.jar
PrivateMessager-v1.0.jar
ProtectYourChest.jar
SudoChat.jar
SuperVanish-6.2.6.jar
SystemEnchants.jar 
TabList-bukkit-5.6.0.jar
TrollBoss_v6.3.7.jar
UltraCosmetics-2.5.11-RELEASE.jar
VoidGenerator.jar 
WarpNPCs+v1.0.2419.jar 
worldedit-bukkit-7.2.7.jar 
worldguard-bukkit-7.0.6-dist.jar

### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
```
09.01 08:45:00 [Server] ERROR Could not pass event InventoryCreativeEvent to UltraCosmetics v2.5.11
```

**Comment by datatags** [comment] 2022-01-09 21:11
Duplicate of #515, which was fixed in dev builds (see #beta-testing in the Discord)

**Closed by datatags** 2022-01-09 21:11 UTC
