### ISSUE TITLE
Error appears if you log in into the server

### ISSUE THREAD

**Issue by itaquito** [iSach/UltraCosmetics#494] opened 2020-06-09 18:20 UTC
### What steps will reproduce the issue?  
1. Log in into the server

### What was supposed to happen?
An error should appear if a player logins into the server.

### What happened? 
An error appeared when a player joined the server.
Error: https://pastebin.com/FDNwpJZr

### What version of UltraCosmetics are you using?  
`UltraCosmetics-2.5.7-RELEASE`

### What Spigot version are you using? Paste the output of /version below.  
```
[16:54:59 INFO]: Checking version, please wait...
[16:54:59 INFO]: This server is running Paper version git-Paper-334 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
[16:55:00 INFO]: You are 11 version(s) behind
[16:55:00 INFO]: Previous version: git-Paper-217 (MC: 1.15.2)
```

### What plugins do you have installed? Paste the output of /plugins below.  
`[16:55:16 INFO]: Plugins (29): AdvancedPortals, BungeeTabListPlus, Citizens, CustomJoinMessages*, DeluxeMenus, Essentials, FastAsyncWorldEdit, FeatherBoard*, HolographicDisplays, HolographicExtension, ItemJoin, JumpPads, LeakParkour, LevelPoints, LoginStreak, LuckPerms, MVdWPlaceholderAPI*, PlaceholderAPI, Plan, ProtocolLib, SetTheSpawn, SuperVanish, TreysDoubleJump, UltraCosmetics, Vault, VoidGenerator, VoidSpawn, WorldEdit, WorldGuard`

### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
```
[18:11:46 WARN]: [UltraCosmetics] Plugin UltraCosmetics v2.5.7 generated an exception while executing task 1473
java.lang.IllegalStateException: Asynchronous entity add!
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.15.2.jar:git-Paper-334]
        at net.minecraft.server.v1_15_R1.WorldServer.addEntity0(WorldServer.java:1236) ~[patched_1.15.2.jar:git-Paper-334]
        at net.minecraft.server.v1_15_R1.WorldServer.addEntity(WorldServer.java:1173) ~[patched_1.15.2.jar:git-Paper-334]
        at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.addEntity(CraftWorld.java:1951) ~[patched_1.15.2.jar:git-Paper-334]
        at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.spawn(CraftWorld.java:1958) ~[patched_1.15.2.jar:git-Paper-334]
        at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.spawn(CraftWorld.java:1542) ~[patched_1.15.2.jar:git-Paper-334]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
        at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.spawnEntity(CraftWorld.java:768) ~[patched_1.15.2.jar:git-Paper-334]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
        at be.isach.ultracosmetics.cosmetics.mounts.MountHorse.onEquip(MountHorse.java:37) ~[?:?]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-334]
        at be.isach.ultracosmetics.cosmetics.mounts.MountEcologistHorse.onEquip(MountEcologistHorse.java:36) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-334]
        at be.isach.ultracosmetics.cosmetics.Cosmetic.equip(Cosmetic.java:63) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-334]
        at be.isach.ultracosmetics.cosmetics.type.CosmeticType.equip(CosmeticType.java:55) ~[?:?]
        at be.isach.ultracosmetics.listeners.PlayerListener$1.run(PlayerListener.java:74) ~[?:?]
        at be.isach.ultracosmetics.player.profile.CosmeticsProfile.loadToPlayer(CosmeticsProfile.java:151) ~[?:?]
        at be.isach.ultracosmetics.player.profile.CosmeticsProfileManager.initForPlayer(CosmeticsProfileManager.java:54) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
```
### Any additional information that you would like to provide that may be relevant to the issue?
No, thanks :D

**Comment by datatags** [comment] 2022-01-14 01:12
Seems to be the same root cause as #529 so I'm gonna close this.

**Closed by datatags** 2022-01-14 01:12 UTC
