### ISSUE TITLE
Gettings Emote heads when equiped

### ISSUE THREAD

**Issue by Zairce** [iSach/UltraCosmetics#527] opened 2020-12-24 10:33 UTC
### What steps will reproduce the issue?  
1. Select an Emote
2. Go into your inventory
3. Remove the emote as you would a helmet

### What was supposed to happen?
It should stay on the head without giving a free emote head, like happens when you try it for a hat
### What happened? 
You can just keep clicking it and get loads of heads from the emote
### What version of UltraCosmetics are you using?  
2.5.10
### What Spigot version are you using? Paste the output of /version below.  
![image](https://user-images.githubusercontent.com/71657981/103082921-87986d00-45db-11eb-8654-14c690621bcf.png)

### What plugins do you have installed? Paste the output of /plugins below.  
![image](https://user-images.githubusercontent.com/71657981/103082988-a4cd3b80-45db-11eb-8556-13d988f04c3d.png)
![image](https://user-images.githubusercontent.com/71657981/103083019-b1519400-45db-11eb-9fe2-1e201756f980.png)

### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
```
No Errors in console

### Any additional information that you would like to provide that may be relevant to the issue?
It only happens for emotes, not for hats.

**Comment by Baterka** [comment] 2021-05-18 15:53
This problem still persist

**Comment by datatags** [comment] 2022-01-01 21:58
Duplicate of #515, which was fixed.

**Closed** 2022-01-01 21:58 UTC
