### ISSUE TITLE
Not checking if version above 1.13 for differences in DyeColor in BlockUtils

### ISSUE THREAD

**Issue by dode5656** [iSach/UltraCosmetics#477] opened 2020-03-22 12:50 UTC
### What steps will reproduce the issue?  
1. Use Paintball Gadget
2. Keep trying till you try to place light gray stained clay

### What was supposed to happen?
Place light gray stained clay

### What happened? 
Didn't place light gray stained clay and an error occurred

### What version of UltraCosmetics are you using?  
2.5.7

### What Spigot version are you using? Paste the output of /version below.  
```
[13:41:36 INFO]: This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[13:41:36 INFO]: Previous version: git-Paper-653 (MC: 1.13.2)
[13:41:36 INFO]: Checking version, please wait...
[13:41:36 INFO]: You are running the latest version
```

### What plugins do you have installed? Paste the output of /plugins below.  
Issue not related to other plugins, its a bug report

### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
https://hastebin.com/voqaseweve.cs

### Any additional information that you would like to provide that may be relevant to the issue?
Error caused by [this](https://github.com/iSach/UltraCosmetics/blob/master/core/src/main/java/be/isach/ultracosmetics/util/BlockUtils.java#L260) not being checked to be 1.13+ or no  because as its shown [here](https://helpch.at/docs/1.12.2/index.html?org/bukkit/DyeColor.html) its called SILVER and not LIGHT_GRAY

**Comment by datatags** [comment] 2022-01-10 22:36
Duplicate of #463, which was resolved.

**Closed by datatags** 2022-01-10 22:36 UTC
