### ISSUE TITLE
/uc treasure not working

### ISSUE THREAD

**Issue by bighead0901** [iSach/UltraCosmetics#526] opened 2020-12-19 13:49 UTC
### What steps will reproduce the issue?  
/uc treasure is not working properly
eg
typing /uc treasure name 125 80 -47 world
Player is tped to 125.5 80 -46.5 but NO treasure chest is opened, instead "an internal error" msg is displayed with following console error: https://pastebin.com/T4RQNpVp
Player has treasure key and permission

### What version of UltraCosmetics are you using?  
Latest version for 1.16.4

### What Spigot version are you using? Paste the output of /version below.  
CraftBukkit version git-Spigot-628435a-768d7fc (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
(Latest version)

### What plugins do you have installed? Paste the output of /plugins below.  
 UltimateFishing, BattleTraining, PlaceholderAPI, WeaponHolder, PlugMan, BetterChairs, PingPlayer, Core, AdvancedHelp, Infinianvil, TitleAPI, Lib1711, VoxelSniper, NoteBlockAPI, WaterDamage, LightAPI, LuckPerms, wAnvils, CombatWeaponryPlus, QuickBoard, LoneLibs, MinecraftServerManager, ProtocolLib, GraveEntitySpawn, LibsDisguises, NoCheatPlus, MVdWPlaceholderAPI, FastAsyncWorldEdit, ChristmasPresents, ImageOnMap, LevelChat, MaxLevelCap, AntiAura, Vault, PSnow, GMusic, PlayerProfiles, UltraCosmetics, HolographicDisplays, GravityTubes, CustomHeads, WorldEdit, Essentials, MarriageMaster, ItemEdit, TreasureChest, Citizens, BentoBox, DeluxeMenus, EssentialsChat, WorldGuard, LockettePro, EssentialsProtect, BanItem, EssentialsAntiBuild, ServerSigns, NexEngine, CitizensGUI, EssentialsSpawn, MarriageMasterGUI, Jobs, Multiverse-Core, Shopkeepers, ArtMap, GoldenCrates, QuantumShop, ProtectionLib, NonSquareMines, ServerTutorialPlus, UltimateTimber

### Are any errors related to UltraCosmetics in your console or logs? If so, paste below.  
org.bukkit.command.CommandException: Unhandled exception executing command 'uc' in plugin UltraCosmetics v2.5.10
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.16.4.jar:git-Spigot-628435a-768d7fc]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.16.4.jar:git-Spigot-628435a-768d7fc]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:763) ~[spigot-1.16.4.jar:git-Spigot-628435a-768d7fc]
	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:1788) ~[spigot-1.16.4.jar:git-Spigot-628435a-768d7fc]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1631) ~[spigot-1.16.4.jar:git-Spigot-628435a-768d7fc]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1584) ~[spigot-1.16.4.jar:git-Spigot-628435a-768d7fc]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.16.4.jar:git-Spigot-628435a-768d7fc]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.16.4.jar:git-Spigot-628435a-768d7fc]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.4.jar:git-Spigot-628435a-768d7fc]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[spigot-1.16.4.jar:git-Spigot-628435a-768d7fc]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.4.jar:git-Spigot-628435a-768d7fc]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.4.jar:git-Spigot-628435a-768d7fc]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.4.jar:git-Spigot-628435a-768d7fc]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:942) ~[spigot-1.16.4.jar:git-Spigot-628435a-768d7fc]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:935) ~[spigot-1.16.4.jar:git-Spigot-628435a-768d7fc]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.4.jar:git-Spigot-628435a-768d7fc]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:919) ~[spigot-1.16.4.jar:git-Spigot-628435a-768d7fc]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:851) ~[spigot-1.16.4.jar:git-Spigot-628435a-768d7fc]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.4.jar:git-Spigot-628435a-768d7fc]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NullPointerException
	at be.isach.ultracosmetics.manager.TreasureChestManager.tryOpenChest(TreasureChestManager.java:72) ~[?:?]
	at be.isach.ultracosmetics.command.subcommands.SubCommandTreasure.common(SubCommandTreasure.java:102) ~[?:?]
	at be.isach.ultracosmetics.command.subcommands.SubCommandTreasure.onExePlayer(SubCommandTreasure.java:33) ~[?:?]
	at be.isach.ultracosmetics.command.CommandManager.onCommand(CommandManager.java:105) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.16.4.jar:git-Spigot-628435a-768d7fc]
	... 19 more

**Comment by datatags** [comment] 2021-12-31 02:27
This is caused by opening a treasure chest near player NPCs. Fixed in dev builds, which can be found in Discord.

**Closed by datatags** 2021-12-31 02:27 UTC
